name: Validate Issue Template

on:
  issues:
    - opened
    - edited
    - reopened

jobs:
  check_title:
   runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-label "triage" 
